version: '3'

services:
    cubasuper-db:
        container_name: cubasuper-db
        image: postgres:latest
        ports:
          - "5432:5432"
        volumes:
          - /data/postgres:/data/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        restart: unless-stopped
        networks:
          - postgres

    cubasuper-api:
        container_name: cubasuper-api
        image: oljimenez/cubasuper:api
        extra_hosts:
          - "host.docker.internal:host-gateway"
        ports:
          - "8000:8000"
        env_file:
          - .env
        restart: unless-stopped
        expose:
          - 8000
        depends_on:
          - cubasuper-db
        networks:
          - postgres

    cubasuper-web:
        container_name: cubasuper-web
        image: oljimenez/cubasuper:web
        ports:
          - "3000:3000"
        expose:
          - 3000
        env_file:
          - .env
        restart: unless-stopped
        depends_on:
          - cubasuper-db
          - cubasuper-api
        networks:
          - postgres

networks:
    postgres:
        driver: bridge