# Generated by Django 4.1.4 on 2023-01-02 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Información')),
                ('info_trans', models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Traducción de la información')),
            ],
            options={
                'verbose_name': 'Información',
                'verbose_name_plural': 'Informaciones',
            },
        ),
        migrations.CreateModel(
            name='AsociationProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Asociación de productos',
                'verbose_name_plural': 'Asociaciones de productos',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500, verbose_name='No. Serie')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Imagen')),
                ('promoted', models.BooleanField(default=False, verbose_name='Especial')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción del nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('email', models.EmailField(error_messages={'unique': 'Un contacto con este correo ya existe'}, max_length=254, unique=True, verbose_name='Correo del contacto')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('phone_number', models.CharField(error_messages={'unique': 'Ya este teléfono está registrado'}, help_text='Debe empezar con "+"', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en este formato: +9999999999. Hasta 15 dígitos permitidos.', regex='\\+?1?\\d{9,15}$')], verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción del nombre')),
            ],
            options={
                'verbose_name': 'Definición',
                'verbose_name_plural': 'Definiciones',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Imagen')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción del nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('description_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción de la descripción')),
                ('unit_of_measurement', models.CharField(max_length=255, verbose_name='unidad de medida')),
                ('unit_of_measurement_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción de la unidad de medida')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Cantidad de inventario')),
                ('visible', models.BooleanField(default=False)),
                ('sales', models.IntegerField(default=0, verbose_name='Ventas')),
                ('sku', models.CharField(help_text='Código interno de la empresa. Opcional', max_length=255, unique=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Recomendado')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batch', to='org.batch')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_definition', to='org.definition', verbose_name='Definición')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['definition', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Imagen')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción del nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('description_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción de la descripción')),
                ('unit_of_measurement', models.CharField(max_length=255, verbose_name='unidad de medida')),
                ('unit_of_measurement_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción de la unidad de medida')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('stock', models.IntegerField(blank=True, help_text='El sistema determinará la disponibilidad', null=True, verbose_name='Cantidad de inventario')),
                ('visible', models.BooleanField(default=False)),
                ('sales', models.IntegerField(default=0, verbose_name='Ventas')),
                ('sku', models.CharField(blank=True, help_text='Código interno de la empresa. Opcional', max_length=255, null=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Recomendado')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_batch', to='org.batch')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_definition', to='org.definition')),
                ('products', models.ManyToManyField(related_name='group_of_products', through='org.AsociationProductGroup', to='org.product')),
            ],
            options={
                'verbose_name': 'Agrupación de productos',
                'verbose_name_plural': 'Agrupaciones de productos',
                'ordering': ['definition', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nombre del slider', max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='silderitems/', verbose_name='Imagen')),
                ('visible', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(choices=[(1, 'Arriba'), (2, 'Medio'), (3, 'Abajo')], verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Información')),
                ('info_trans', models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Traducción de la información')),
            ],
            options={
                'verbose_name': 'Términos y condiciones',
                'verbose_name_plural': 'Términos y condiciones',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('name_trans', models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Traducción del nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='org.category')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_images/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_images', to='org.productgroup')),
            ],
            options={
                'verbose_name': 'Imagen de grupo de productos',
                'verbose_name_plural': 'Imágenes de grupo de productos',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='org.product')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.CharField(max_length=900, primary_key=True, serialize=False, unique=True)),
                ('date_of_creation', models.DateTimeField()),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-date_of_creation'],
            },
        ),
        migrations.AddField(
            model_name='definition',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition_subcategory', to='org.subcategory'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_product', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Real')),
                ('quantity', models.IntegerField()),
                ('actual_amount', models.FloatField(blank=True, null=True, verbose_name='Cantidad Real')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='component_group', to='org.productgroup', verbose_name='Grupo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_order', to='org.order')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='component_product', to='org.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.AddField(
            model_name='asociationproductgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociated_group', to='org.productgroup'),
        ),
        migrations.AddField(
            model_name='asociationproductgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociated_product', to='org.product'),
        ),
        migrations.AlterUniqueTogether(
            name='asociationproductgroup',
            unique_together={('product', 'group')},
        ),
    ]
