# Generated by Django 4.1.4 on 2023-01-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='Ejemplo: 123.6.56.189, mail.cubasuper.com', max_length=255, verbose_name='Host del correo')),
                ('email_host_user', models.CharField(help_text='Ejemplo: no-reply@cubasuper.com', max_length=255, verbose_name='Correo ')),
                ('email_host_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña ')),
                ('email_host_port', models.PositiveSmallIntegerField(verbose_name='Puerto')),
                ('email_use_tsl', models.BooleanField(default=False, verbose_name='TSL')),
                ('email_use_ssl', models.BooleanField(default=True, verbose_name='SSL')),
                ('email_timeout', models.PositiveSmallIntegerField(default=5, verbose_name='Tiempo de espera')),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuración de correo',
            },
        ),
    ]
